apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
  labels:
    app: web
data:
  RUN_ID: 765cadc38c2c4aeb8164eadd0f27265a
  TRACKING_URI: http://host.docker.internal:5000
  EXPERIMENT: online-course-engagement-prediction-experiment-1